name: Build Kodi Addon

on:
  push:
    tags:
      - "v*"    # 例如 v1.0.0 时触发
  workflow_dispatch:   # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set variables
        id: vars
        run: |
          ADDON_ID=$(basename $(find . -maxdepth 1 -type d -name "plugin.*" -o -name "script.*"))
          echo "ADDON_ID=$ADDON_ID" >> $GITHUB_ENV
          VERSION=$(grep -oP 'version="\K[^"]+' $ADDON_ID/addon.xml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Addon ID: $ADDON_ID"
          echo "Version: $VERSION"

      - name: Create zip
        run: |
          mkdir dist
          zip -r "dist/${ADDON_ID}-${VERSION}.zip" "$ADDON_ID" -x "*.git*" -x "docs/*" -x ".vscode/*" -x "*.github/*" -x "dist/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ADDON_ID }}-${{ env.VERSION }}
          path: dist/*.zip

      - name: Upload release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
